# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SelectDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SelectDemo

  target 'SelectDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'WMPageController'
  pod "TTGTagCollectionView"
  pod 'Masonry'
  
  target 'SelectDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
